name: Deploy on Build Failure

on:
 workflow_run:
    workflows: ["Java CI"]
    types:
      - completed

jobs:
 deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy existing artifact
        uses: Itzbenz/mindustry-plugin-deploy-to-pterodactyl@016baa1e8b1210c4c61cf1235e1cdfeda469e382
        with:
          artifact: build/libs/YES-3.jar
          endpoint: ${{secrets.PTERODACTYL_ENDPOINT}}
          server: ${{secrets.TOWERDEFENSE_SERVER_ID}}
          token: ${{secrets.PTERODACTYL_API_KEY }}
          restart: true